// <auto-generated />
using System;
using Habitus.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Habitus.Infrastructure.Migrations
{
    [DbContext(typeof(HabitusDbContext))]
    [Migration("20260530105500_DropLegacyCondominiumTaxId")]
    partial class DropLegacyCondominiumTaxId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Habitus.Domain.Entities.Condominium", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("PaymentBankTransferEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PaymentCardEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PaymentIban")
                        .HasColumnType("text");

                    b.Property<string>("PaymentIbanEncrypted")
                        .HasColumnType("text");

                    b.Property<string>("PaymentInstructions")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMbReference")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMbWay")
                        .HasColumnType("text");

                    b.Property<bool>("PaymentMbWayEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxIdEncrypted")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Condominiums");
                });
        }
    }
}